[package]
name = "ccc-rust"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]

[dependencies]
# iron = "0.6.0"
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
serde = "1.0.70"
serde_derive = "1.0.70"
reqwest = "0.8.7"
