version: '3'
services:
  proxy:
    image: nginx:alpine@sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx

  carleton:
    image: frogpond/ccc-server:master
    restart: unless-stopped
    environment:
      INSTITUTION: carleton-college
    volumes:
      - ./.env:/app/.env:ro

  stolaf:
    image: frogpond/ccc-server:master
    restart: unless-stopped
    environment:
      INSTITUTION: stolaf-college
    volumes:
      - ./.env:/app/.env:ro
