version: '3'
services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx:/etc/nginx/conf.d:ro

  carleton:
    image: frogpond/ccc-server:HEAD
    restart: unless-stopped
    environment:
      INSTITUTION: carleton-college

  stolaf:
    image: frogpond/ccc-server:HEAD
    restart: unless-stopped
    environment:
      INSTITUTION: stolaf-college
