[tools]
node = "24.11.0"

[tasks.p]
run = "mise run pretty -- --no-write --check"
alias = "pretty:check"

[tasks.pretty]
run = "prettier --write source scripts"
env = { _.path = ['{{config_root}}/node_modules/.bin'] }

[tasks.format]
run = { task = "pretty" }

[tasks.lint]
run = "eslint --cache --max-warnings=0 ."
env = { _.path = ['{{config_root}}/node_modules/.bin'] }

[tasks.start]
run = "node source/ccc-server/index.ts"

[tasks."start:watch"]
run = "node --watch source/ccc-server/index.ts"

[tasks."start:prod"]
run = { task = "start" }
env = { NODE_ENV = "production" }

[tasks."stolaf-college"]
run = "mise run start"
env = { INSTITUTION = "stolaf-college" }

[tasks."carleton-college"]
run = "mise run start"
env = { INSTITUTION = "carleton-college" }

[tasks."test:stolaf-college"]
run = "./scripts/smoke-test.sh stolaf-college"

[tasks."test:carleton-college"]
run = "./scripts/smoke-test.sh carleton-college"

[tasks.test]
run = "node --test"

[tasks.watch]
depends = "build"                                # build once, before starting
run = { tasks = ["build:watch", "start:watch"] }

[tasks.typecheck]
run = "tsc --build ."
env = { _.path = ['{{config_root}}/node_modules/.bin'] }

[tasks."typecheck:watch"]
run = "mise run typecheck --watch"

[tasks.check]
run = { tasks = ["p", "lint", "test", "typecheck"] }
