[tools]
node = "22.20.0"

[tasks.build]
run = "rm -rf ./dist ./.tsbuildinfo && ./node_modules/.bin/tsc"
sources = ["source/**/*.ts", "types/**/*.ts", "tsconfig.json"]
outputs = ["dist/"]

[tasks."build:watch"]
run = "./node_modules/.bin/tsc --watch"

[tasks.p]
run = "mise run pretty -- --no-write --check"
alias = "pretty:check"

[tasks.pretty]
run = "./node_modules/.bin/prettier --write source scripts"

[tasks.lint]
run = "./node_modules/.bin/eslint --cache --max-warnings=0 ."

[tasks.start]
run = "node dist/source/ccc-server/index.js"
depends = ["build"]

[tasks."start:watch"]
run = "node --watch dist/source/ccc-server/index.js"
env = { NODE_ENV = "development" }
depends = ["build"]

[tasks."start:dev"]
run = "node dist/source/ccc-server/index.js"
env = { NODE_ENV = "development" }
depends = ["build"]

[tasks."start:prod"]
run = "node dist/source/ccc-server/index.js"
env = { NODE_ENV = "production" }
depends = ["build"]

[tasks."stolaf-college"]
run = "node dist/source/ccc-server/index.js"
env = { NODE_ENV = "development", INSTITUTION = "stolaf-college" }
depends = ["build"]

[tasks."carleton-college"]
run = "node dist/source/ccc-server/index.js"
env = { NODE_ENV = "development", INSTITUTION = "carleton-college" }
depends = ["build"]

[tasks."test:stolaf-college"]
run = "./scripts/smoke-test.sh stolaf-college"
depends = ["build"]

[tasks."test:carleton-college"]
run = "./scripts/smoke-test.sh carleton-college"
depends = ["build"]

[tasks.test]
run = "./node_modules/.bin/vitest run"

[tasks.watch]
depends = ["build"]
run = '''
#!/usr/bin/env bash
mise run build:watch & mise run start:watch & wait
'''

[tasks.typecheck]
run = "./node_modules/.bin/tsc --noEmit"

[tasks.check]
depends = ["p", "lint", "test", "typecheck"]
run = "echo 'All checks passed!'"
