# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
  merge_group:

jobs:
  # This job runs all the primary checks: linting, formatting, type checking, and unit tests.
  # It is the equivalent of the old `build`, `test`, `lint`, and `format` jobs combined.
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3
      - run: npm ci
      - run: mise run check

  smoke-test-stolaf:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3
      - run: npm ci
      - run: mise run test:stolaf-college

  smoke-test-carleton:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3
      - run: npm ci
      - run: mise run test:carleton-college