# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
  merge_group:

jobs:
  # This job runs all the primary checks: linting, formatting, type checking, and unit tests.
  # It is the equivalent of the old `build`, `test`, `lint`, and `format` jobs combined.
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      - run: npm ci
      - run: mise run check

  smoke-test-stolaf:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      - run: npm ci
      - run: mise run test:stolaf-college

  smoke-test-carleton:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      - run: npm ci
      - run: mise run test:carleton-college