# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/setup-mise@v2
      - run: npm ci
      - run: mise run check

  smoke-test-stolaf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/setup-mise@v2
      - run: npm ci
      - run: mise run test:stolaf-college

  smoke-test-carleton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/setup-mise@v2
      - run: npm ci
      - run: mise run test:carleton-college